return {
--  "folke/noice.nvim",
--  opts = {
--    
--  },
--  dependencies = {
--    "MunifTanjim/nui.nvim",
--    "rcarriga/nvim-notify"
--  },
--  config = function ()
--    require("noice").setup({
--      lsp = {
--        overide = {
--          ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
--          ["vim.lsp.util.stylize_markdown"] = true,
--          ["cmp.entry.get_documentation"] = true,
--        },
--      },
--      presets = {
--        command_palette = true,
--        lsp_doc_border = true,
--      }
--    })
--  end
}
